// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTBMsIRoCktgyNCy8gwjEWt2fCrvNvhMc',
    appId: '1:503645418605:web:db3f180c549e3a78e0fb64',
    messagingSenderId: '503645418605',
    projectId: 'test-app-fd3aa',
    authDomain: 'test-app-fd3aa.firebaseapp.com',
    storageBucket: 'test-app-fd3aa.firebasestorage.app',
    measurementId: 'G-4EP2PEHVZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmR2ZRlZ7YyUk0rIxuqTBjkjW4s_gsevA',
    appId: '1:503645418605:android:d6a2795e4598e981e0fb64',
    messagingSenderId: '503645418605',
    projectId: 'test-app-fd3aa',
    storageBucket: 'test-app-fd3aa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTBMsIRoCktgyNCy8gwjEWt2fCrvNvhMc',
    appId: '1:503645418605:web:58639c51047f3297e0fb64',
    messagingSenderId: '503645418605',
    projectId: 'test-app-fd3aa',
    authDomain: 'test-app-fd3aa.firebaseapp.com',
    storageBucket: 'test-app-fd3aa.firebasestorage.app',
    measurementId: 'G-J9Y8V28RY7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8EAtDscaamZsd47C-FFGxyo0YZED4aw',
    appId: '1:503645418605:ios:79e110d5ec61664be0fb64',
    messagingSenderId: '503645418605',
    projectId: 'test-app-fd3aa',
    storageBucket: 'test-app-fd3aa.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8EAtDscaamZsd47C-FFGxyo0YZED4aw',
    appId: '1:503645418605:ios:79e110d5ec61664be0fb64',
    messagingSenderId: '503645418605',
    projectId: 'test-app-fd3aa',
    storageBucket: 'test-app-fd3aa.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

}